version: '3'

services:
  app:
    build: flask
    ports:
      - "5000:5000"
    depends_on:
      - redis  
  redis:
    image: "redis:alpine"
  proxy:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app